decipher/challenge/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from . import forms


app_name = 'challenge'

# Decipher challenge urls
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('challenges_page/',
         views.ChallengesPageView.as_view(),
         name='challenges_page'
        ),
    path('challenge/', views.ChallengeView.as_view(), name='challenge'),
    path('rules/', views.RulesView.as_view(), name='rules'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('ranking/', views.RankingView.as_view(), name='ranking'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password_change/', views.PasswordChangeView.as_view(),
         name='password_change'
        ),

    # password reset module (lost password)
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name='challenge/password_reset.html'
         ),
         name='password_reset'
        ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='challenge/password_reset_done.html'
         ),
         name='password_reset_done'
        ),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=forms.PasswordResetConfirmForm,
             template_name='challenge/password_reset_confirm.html'
         ),
         name='password_reset_confirm'
        ),
    path('reset/done/',
         views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'
        ),
]

decipher/decipher/urls.py
from django.contrib import admin
from django.urls import path, include
from challenge.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('challenge/', include('challenge.urls', namespace='challenge')),
    path('challenge/', include('django.contrib.auth.urls')),
    path('',  IndexView.as_view(), name='index'),
]

decipher/challenge/models.py
import json
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings



# Our personalized decipher challenge user model. We could use the default
# Django user model, but then it wouldn't be possible to add attributes to it
class User(AbstractUser):

    # which challenges have been done
    initial_val = ['0' for i in range(settings.NUMBER_OF_CHALLENGES)]
    initial_val = json.dumps(initial_val)
    challenges_done = models.TextField(default=initial_val)

    # points that user got
    points = models.PositiveIntegerField(default=0)

    # ranking tiebreaker
    last_capture = models.DateTimeField(default=None, null=True, blank=True)



# Challenges model
class Challenge(models.Model):
    id_chall = models.PositiveIntegerField(primary_key=True, unique=True)
    title = models.CharField(max_length=200, unique=True)
    type_chall = models.CharField(max_length=20)
    file_content = models.TextField()
    description = models.TextField()
    points = models.PositiveIntegerField(default=0)
    flag = models.CharField(max_length=200)
    solved_by = models.PositiveIntegerField(default=0)

decipher/challenge/views.py
'''
Decipher challenge views
'''
from datetime import datetime
from hashlib import sha256
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, View
from django.contrib import messages
from django.utils import timezone
from django.conf import settings

from .models import User, Challenge
from . import forms

class IndexView(TemplateView):

    # Redirect to the home page
    def dispatch(self, request, *args, **kwargs):
        return redirect('challenge:home')



class HomeView(TemplateView):

    template_name = 'challenge/home.html'



class ChallengesPageView(LoginRequiredMixin, View):

    template_name = 'challenge/challenges_page.html'

    def get(self, request):

        # if authenticated, pass the challenges to the template
        if request.user.is_authenticated:
            challs = list(Challenge.objects.all().values())

            # concatenate challenge info with field that
            # says if user has unlocked or not the challenge
            # and info that says if user has done ir ot not
            challenges_done = json.loads(request.user.challenges_done)

            # total number of users
            n_users = len(User.objects.all())

            # if there's at least one user, compute percentage
            if n_users > 0:
                for i in range(0, len(challs)):
                    challs[i]['solved_by'] = challs[i]['solved_by'] / n_users
                    challs[i]['solved_by'] *= 100
            # if there's no user, just set it to zero
            else:
                for i in range(0, len(challs)):
                    challs[i]['solved_by'] = 0

            if settings.SEQUENTIAL_CHALLENGES:

                # for sequential challenges, challenge 0 may be done or
                # not, but is always unlocked for everybody
                challs[0]['is_done'] = challenges_done[0]
                challs[0]['locked'] = '0'

                # from challenge 1 onwards, we need to verify if
                # it's unlocked or not
                for i in range(1, len(challs)):
                    if challenges_done[i] == '1':
                        is_done = '1'
                        locked = '0'
                    elif challenges_done[i - 1] == '1':
                        is_done = '0'
                        locked = '0'
                    else:
                        is_done = '0'
                        locked = '1'
                    challs[i]['is_done'] = is_done
                    challs[i]['locked'] = locked

            # for non sequential challenges, every challenge is unlocked
            else:
                for i in range(0, len(challs)):
                    is_done = challenges_done[i]
                    locked = '0'
                    challs[i]['is_done'] = is_done
                    challs[i]['locked'] = locked

            return render(
                request, self.template_name,
                {'challenges' : challs,
                 'sequential' : settings.SEQUENTIAL_CHALLENGES}
            )

        # otherwise, don't
        return render(request, self.template_name)



class ChallengeView(LoginRequiredMixin, View):

    template_name = 'challenge/challenge.html'
    form_class = forms.ChallengeForm

    def post(self, request):

        form = self.form_class(request.POST)

        chall = get_object_or_404(
            Challenge,
            id_chall=request.POST['id_chall']
        )

        # challenges done by user
        challenges_done = json.loads(request.user.challenges_done)

        # user isn't allowed to check this challenge
        if settings.SEQUENTIAL_CHALLENGES:
            if chall.id_chall != 0:
                if challenges_done[chall.id_chall - 1] == '0':
                    return redirect('challenge:index')

        # 'link type challenge', so open the link file to
        # pass the link to template
        if chall.type_chall == 'link':
            file_path = "challenge/static/" + chall.file_content
            file_object = open(file_path, 'r')
            link = file_object.read()
        else:
            link = None

        # we're gonna use this to show specific errors to users
        flag_resubmission = False
        wrong_flag = False

        # check if it's a flag submission
        if "flag" in request.POST.keys():

            # guarantee that's not a resubmission
            if challenges_done[chall.id_chall] == '0':

                # now let's check if the flag is correct
                flag = request.POST['flag']
                hash_flag = sha256(bytes(flag, 'utf-8')).hexdigest()

                # flag is correct
                if hash_flag == chall.flag:

                    challenges_done[chall.id_chall] = '1'
                    request.user.challenges_done = json.dumps(challenges_done)
                    request.user.points += chall.points
                    request.user.last_capture = datetime.now(tz=timezone.utc)
                    chall.solved_by += 1
                    request.user.save()
                    chall.save()

                    return redirect('challenge:challenges_page')

                # otherwise the flag is incorrect
                wrong_flag = True

            # it's a resubmission
            else:
                flag_resubmission = True

        # select the 'correct error' to show
        error_message = None
        if flag_resubmission:
            error_message = "You have already completed this challenge."
        elif wrong_flag:
            error_message = "Wrong flag :("

        # total number of users
        n_users = len(User.objects.all())

        # percentage of users that solved this challenge
        if n_users > 0:
            chall.solved_by = chall.solved_by / n_users
            chall.solved_by *= 100
        # if there's no user, just set it to zero
        else:
            chall.solved_by = 0

        # render the challenge page
        return render(
            request, self.template_name,
            {'error_message' : error_message, 'link' : link,
             'challenge': chall, 'form' : form}
        )



class RulesView(LoginRequiredMixin, TemplateView):

    template_name = 'challenge/rules.html'



class RegisterView(TemplateView):

    template_name = 'challenge/register.html'
    form_class = forms.RegisterForm

    # Render register page
    def get(self, request, *args, **kwargs):

        # Redirect to index if user is already logged in
        if request.user.is_authenticated:
            return redirect('challenge:index')


        # Otherwise show form to register
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    # Deal with register request
    def post(self, request):

        form = self.form_class(request.POST)

        # If the form is valid create new user object
        if form.is_valid():
            messages.success(request, 'Registration successful.')
            User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
                email=form.cleaned_data['email'],
                points=0,
                last_capture=datetime.now(tz=timezone.utc),
            )
            # Redirect new user to login page
            return redirect('challenge:login')

        # Otherwise render register page again
        return render(request, self.template_name, {'form': form})



class LoginView(TemplateView):

    template_name = 'challenge/login.html'
    form_class = forms.LoginForm

    # Render login page
    def get(self, request, *args, **kwargs):

        # If the user is already logged redirect him to index
        if request.user.is_authenticated:
            return redirect('challenge:index')

        # Otherwise show him the forms
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    # Handle login attempt
    def post(self, request):

        form = self.form_class(request.POST)

        # Check if the attempt is valid
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            # If valid user, redirect to index page
            if user is not None:
                login(request, user)
                return redirect('challenge:index')
            # Otherwise spawn invalid login message
            form.invalidLoginMessage()

        # Show the login page again (with invalid login message)
        return render(request, self.template_name, {'form': form})



class RankingView(LoginRequiredMixin, View):

    template_name = 'challenge/ranking.html'

    def get(self, request):

        ranking = []
        users = User.objects.filter(is_staff=False)
        ranking = users.order_by('-points', 'last_capture')

        return render(request, self.template_name, {'ranking': ranking})



class LogoutView(LoginRequiredMixin, View):

    template_name = 'challenge/ranking.html'

    def get(self, request):

        logout(request)
        return redirect('challenge:index')



class PasswordChangeView(LoginRequiredMixin, TemplateView):

    template_name = 'challenge/password_change.html'
    form_class = forms.PasswordChangeForm

    # Render change password form
    def get(self, request, *args, **kwargs):

        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    # Handle password change attempt
    def post(self, request):

        form = self.form_class(request.POST)

        # If the form is valid change user password
        if form.is_valid():

            # Get user object

decipher/challenge/templates/challenge/base.html
{% load static %}
<!doctype html>
<html>
  <head>

    <!-- css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <!-- Cool icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Control layout on mobile browsers -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon and page title -->
    <link rel='shortcut icon' type='image/x-icon' href="{% static "assets/favicon.ico" %}"/>
    <title> {% block title %}{% endblock %} </title>

  </head>

  <body>

    {% block menu_items %}

      <nav>
        <div class="nav-wrapper">

          <!-- Desktop dropdown menu options (show on dropdown trigger) -->
          <ul class="dropdown-content" id="dropdown" >
            <li class="menu-item"><a href="{% url 'challenge:password_change' %}">Password change</a></li>
            <li class="divider"></li>
            <li class="menu-item"><a href="{% url 'challenge:logout' %}">Logout</a></li>
          </ul>

          <!-- Desktop navbar menu options -->
          <ul class="hide-on-med-and-down">

            <!-- Always show options -->
            <li>
              <a class="nav-item" href="{% url 'challenge:home' %}">
                Home
              <i class="material-icons left">home</i>
              </a>
            </li>

            <!-- Authenticated user options -->
            {% if request.user.is_authenticated %}
              <li>
                <a class="nav-item" href="{% url 'challenge:rules' %}">
                  Rules
                  <i class="material-icons left">comment</i>
                </a>
              </li>
              <li>
                <a class="nav-item" href="{% url 'challenge:challenges_page' %}">
                  Challenges
                  <i class="material-icons left">extension</i>
                </a>
              </li>
              <li>
                <a class="nav-item" href="{% url 'challenge:ranking' %}">
                  Ranking
                  <i class="material-icons left">star</i>
                </a>
              </li>

              <!-- Dropdown Menu Trigger Button -->
              <li class="right hide-on-med-and-down">
                <a href="#!" class="dropdown-trigger nav-item" id="dropdown-trigger" data-target="dropdown">
                  Account Settings
                  <i class="material-icons left" id="dropdown-icon">
                    account_circle
                  </i>
                </a>
              </li>

            <!-- Not authenticated user options -->
            {% else %}
              <li style="float:right">
                <a class="nav-item" href="{% url 'challenge:register' %}">
                  Register
                  <i class="material-icons left">group_add</i>
                </a>
              </li>
              <li style="float:right">
                <a class="nav-item" href="{% url 'challenge:login' %}">
                  Login
                  <i class="material-icons left">account_circle</i>
                </a>
              </li>
            {% endif %}

          </ul>

          <!--  Sidebar Menu Trigger Button (only show on small screens) -->
          <a href="#" data-target="mobile-demo" class="sidenav-trigger right">
            <i class="material-icons">menu</i>
          </a>

        </div>
      </nav>

      <!-- Mobile sidebar menu options (show on sidebar trigger) -->
      <ul class="sidenav" id="mobile-demo">

        <!-- Always show options -->
        <li>
          <a href="{% url 'challenge:home' %}">
            Home
            <i class="material-icons left">home</i>
          </a>
        </li>

        <!-- Authenticated user options -->
        {% if request.user.is_authenticated %}
          <li>
            <a href="{% url 'challenge:rules' %}">
              Rules
              <i class="material-icons left">comment</i>
            </a>
          </li>
          <li>
            <a href="{% url 'challenge:challenges_page' %}">
              Challenges
              <i class="material-icons left">extension</i>
            </a>
          </li>
          <li>
            <a href="{% url 'challenge:ranking' %}">
              Ranking
              <i class="material-icons left">star</i>
            </a>
          </li>
          <li class="divider"></li>
          <li>
            <a href="{% url 'challenge:password_change' %}">
              Password change
              <i class="material-icons left">edit</i>
            </a>
          </li>
          <li>
            <a href="{% url 'challenge:logout' %}">
              Logout
              <i class="material-icons left">exit_to_app</i>
            </a>
          </li>

        <!-- Not authenticated user options -->
        {% else %}
          <li class="divider" style"margin:0px !important"></li>
          <li>
            <a href="{% url 'challenge:register' %}">
              Register
              <i class="material-icons left">group_add</i>
            </a>
          </li>
          <li>
            <a href="{% url 'challenge:login' %}">
              Login
              <i class="material-icons left">account_circle</i>
            </a>
          </li>
        {% endif %}

      </ul>

    {% endblock %}

    <div id="main_content" class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- JavaScript at end of body for optimized loading -->
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <!-- Our own js file -->
    <script src="{% static "js/base.js" %}"></script>

  </body>
</html>

decipher/challenge/templates/challenge/challenge.html
{% extends 'challenge/base.html' %}
{% load static %}
{% block title %} {{ challenge.title }} {% endblock %}
{% block content %}

    <h4 style="margin-bottom:15pt">
        {{ challenge.title }}
    </h4>

    <div style="margin-bottom:30pt" class="chall-points-solved-by">
      Points for solving: {{ challenge.points }} </br>
      Solved by: {{ challenge.solved_by|floatformat:0 }}% users </p>
    </div>

    {% autoescape off %}
        <div style="margin-bottom:30pt" class="chall-description">
            {{ challenge.description }}
        </div>
    {% endautoescape %}

    {% if challenge.type_chall == 'download' %}
        <h6 style="margin-bottom:30pt">
            <a href="{% static challenge.file_content %}" download>Download needed file</a>
        </h6>
    {% elif challenge.type_chall == 'image' %}
        <h6 style="margin-bottom:30pt">
            <a href="{% static challenge.file_content %}" image>Image needed</a>
        </h6>
    {% elif challenge.type_chall == 'page' %}
        <h6 style="margin-bottom:30pt">
            <a href="{% static challenge.file_content %}" page>Link to challenge</a>
        </h6>
    {% elif challenge.type_chall == 'link' %}
        <h6 style="margin-bottom:30pt">
            <a href={{ link }}>Link to challenge</a>
        </h6>

    {% endif %}


    <form action="{% url 'challenge:challenge' %}" method="post">
        {% csrf_token %}

        <input type="hidden" name="id_chall" value="{{ challenge.id_chall }}">
        <div class="input-field">
            {{ form.flag }}
        </div>
        <button type="submit" class="btn">
            Submit
        </button>
    </form>

    {% if error_message %}
        <div style="margin-top:20pt">
            <b> {{ error_message }} </b>
        </div>
    {% endif %}




{% endblock %}

decipher/challenge/templates/challenge/challenges_page.html
{% extends 'challenge/base.html' %}
{% load static %}

{% block title %}
  Challenges
{% endblock %}

{% block content %}

    {% if request.user.is_authenticated %}

        <h4 style="margin-bottom:30pt">
            Challenges
        </h4>

        {% if challenges %}

          <!-- Only for desktops -->
          <table style="table-layout:fixed" class="hide-on-med-and-down">

            <tr>
              <th style="text-align:center"> Name </th>
              <th style="text-align:center"> Points for solving </th>
              <th style="text-align:center"> Solved by </th>
            </tr>

            {% for chall in challenges %}
              <tr>
                <form action="{% url 'challenge:challenge' %}" method="post">

                    {% csrf_token %}

                    {% if chall.is_done == '1' %}
                      <td style="text-align:center; overflow:hidden">
                        <i class="material-icons" style="vertical-align: middle">lock_open</i>
                        <input type="submit" value="{{ chall.title }}" class="btn chall-name">
                      </td>
                    {% elif chall.is_done == '0' and chall.locked == '1'  %}
                      <td style="text-align:center; overflow:hidden">
                       <i class="material-icons" style="vertical-align: middle">lock</i>
                       <input type="submit" value="{{ chall.title }}" class="btn chall-name" disabled>
                      </td>
                    {% else %}
                      <td style="text-align:center; overflow:hidden">
                        <i class="material-icons" style="vertical-align: middle">lock</i>
                        <input type="submit" value="{{ chall.title }}" class="btn chall-name">
                      </td>
                    {% endif %}

                    <td style="text-align:center; overflow:hidden">
                      <div class="chall_points"> {{ chall.points }} </div>
                    </td>
                    <td style="text-align:center; overflow:hidden">
                      {{ chall.solved_by|floatformat:0 }}% users
                    </td>

                    <input name="id_chall" type="hidden" value="{{ chall.id_chall }}">

                </form>

              </tr>
            {% endfor %}

          </table>

          <!-- Only for tablets/mobiles -->
          <div class="hide-on-large-only">

            {% for chall in challenges %}
              <form action="{% url 'challenge:challenge' %}" method="post" style="float:left; margin-right:30px">

                {% csrf_token %}

                  {% if chall.is_done == '1' %}
                      <i class="material-icons" style="vertical-align: middle">lock_open</i>
                      <input type="submit" value="{{ chall.title }}" class="btn chall-name">
                  {% elif chall.is_done == '0' and chall.locked == '1'  %}
                     <i class="material-icons" style="vertical-align: middle">lock</i>
                     <input type="submit" value="{{ chall.title }}" class="btn chall-name" disabled>
                  {% else %}
                      <i class="material-icons" style="vertical-align: middle">lock</i>
                      <input type="submit" value="{{ chall.title }}" class="btn chall-name">
                  {% endif %}

                  <div class="chall-points">
                    Points for solving: {{ chall.points }}
                  </div>

                  <div class="chall-solved-by">
                    Solved by: {{ chall.solved_by|floatformat:0 }}% users
                  </div>

                  <input name="id_chall" type="hidden" value="{{ chall.id_chall }}">

                </form>

            {% endfor %}

          </div>

        {% else %}
            We still don't have any challenges. Come back soon.
        {% endif %}

    {% endif %}

{% endblock %}

decipher/challenge/templates/challenge/home.html
{% extends 'challenge/base.html' %}
{% load static %}

{% block title %}
  Home
{% endblock %}

{% block content %}

  <img class="home-image" src="{% static "assets/sphinx.svg" %}"></img>

  <!-- Here we have the same text three times because the text size is
       different in differents devices -->
  <div style="text-align: center">
    <p class="hide-on-med-and-down" style="font-size:20px">
      <b>Decipher Me</b> is a free and open web framework to host Jeopardy-style
      Capture The Flag contests. It was built using Django and
      Materialize. Check our
      <a href="https://gitlab.com/enigmaster/decipher-me">GitLab page</a> to
      learn more. If you want to, feel free to change this homepage with your
      own brand. Also, do not feel afraid to contact us and help to improve the
      code!
    </p>
    <p class="hide-on-large-only hide-on-small-only" style="font-size:20px">
      <b>Decipher Me</b> is a free and open web framework to host Jeopardy-style
      Capture The Flag contests. It was built using Django and
      Materialize. Check our
      <a href="https://gitlab.com/enigmaster/decipher-me">GitLab page</a> to
      learn more. If you want to, feel free to change this homepage with your
      own brand. Also, do not feel afraid to contact us and help to improve the
      code!
    </p>
    <p class="hide-on-med-and-up" style="font-size:15px">
      <b>Decipher Me</b> is a free and open web framework to host Jeopardy-style
      Capture The Flag contests. It was built using Django and
      Materialize. Check our
      <a href="https://gitlab.com/enigmaster/decipher-me">GitLab page</a> to
      learn more. If you want to, feel free to change this homepage with your
      own brand. Also, do not feel afraid to contact us and help to improve the
      code!
    </p>
  </div>

{% endblock %}

decipher/challenge/templates/challenge/login.html
{% extends 'challenge/base.html' %}

{% block title %}
  Login
{% endblock %}

{% block content %}

  <!-- Page title -->
  <h4 style="margin-bottom:30px">
    Login
  </h4>

  <!-- Display successful message after user sign up -->
  {% if messages %}
    {% for message in messages %}
      <div class="success-message">{{ message }}</div> <br />
    {% endfor %}
  {% endif %}

  <!-- Display any forms error -->
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="error-message">{{ error }}</div> <br />
      {% endfor %}
    {% endfor %}
  {% endif %}

  <form action="{% url 'challenge:login' %}" method="post">

    <!-- Login form fields -->
    {% csrf_token %}
    {% for field in form %}
      {{ field.label_tag | title }}
      {{ field }}
    {% endfor %}

    <!-- Buttons: confirm login -->
    <input type="submit" value="Enter" class="btn" />

    <a class="btn" href="{% url 'password_reset' %}">
      Reset Password
    </a>

  </form>

{% endblock %}

decipher/challenge/templates/challenge/password_change.html
{% extends 'challenge/base.html' %}

{% block title %}
  Change password
{% endblock %}

{% block content %}

  <!-- Page title -->
  <h4 style="margin-bottom:30px">
    Change password
  </h4>

  <form action="{% url 'challenge:password_change' %}" method="post">

    <!-- Password change form fields -->
    {% csrf_token %}
    {% for field in form %}
      {{ field.label_tag | title }}

      <!-- Display field error message -->
      {% for error in field.errors %}
        <div class="error-message"> {{ error }} </div>
      {% endfor %}

      {{ field }}

    {% endfor %}

    <!-- Button: confirm password change -->
    <input class="btn" type="submit" value="Confirm"/>

  </form>

{% endblock %}

decipher/challenge/templates/challenge/password_reset.html
{% extends 'challenge/base.html' %}

{% block title %}
  Password reset
{% endblock %}

{% block content %}

  <!-- Page title -->
  <h4 style="margin-bottom:30px">
    Password reset
  </h4>

  <form method="post">

    <!-- Password reset form fields -->
    {% csrf_token %}
    {% for field in form %}
      {{ field.label_tag | title }}

      <!-- Display field error message -->
      {% for error in field.errors %}
        <div class="error-message"> {{ error }} </div>
      {% endfor %}

      {{ field }}

    {% endfor %}

    <!-- Button: confirm password reset request (send email) -->
    <input class="btn" type="submit" value="Confirm"/>

  </form>

{% endblock %}

decipher/challenge/templates/challenge/password_reset_confirm.html
{% extends 'challenge/base.html' %}

{% block title %}
  Change password
{% endblock %}

{% block content %}

  <!-- Page title -->
  <h4 style="margin-bottom:30px">
    Change password
  </h4>

  {% if validlink %}

    <form method="post">

      <!-- Register form fields -->
      {% csrf_token %}
      {% for field in form %}
        {{ field.label_tag | title }}

        <!-- Display field error message -->
        {% for error in field.errors %}
          <div class="error-message"> {{ error }} </div>
        {% endfor %}

        {{ field }}

      {% endfor %}

      <!-- Button: confirm password change -->
      <input class="btn" type="submit" value="Confirm"/>

    </form>

    {% else %}
      
      This password reset link is invalid. Please request a new one.

    {% endif %}

{% endblock %}

decipher/challenge/templates/challenge/password_reset_done.html
{% extends 'challenge/base.html' %}
{% block title %}Password reset instructions sent{% endblock %}
{% block content %}

    <h4 style="margin-bottom:30px">
        Password reset instructions sent!
    </h4>

  We've emailed you instructions for setting your password, if an account exists
  with the email you entered. You should receive them shortly.

  If you don't receive an email, please make sure you've entered the address you
  registered with, and check your spam folder.

{% endblock %}

decipher/challenge/templates/challenge/register.html
{% extends 'challenge/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block content %}

  <!-- Page title -->
    <h4 style="margin-bottom:30px">
      Register
    </h4>

  <form action="{% url 'challenge:register' %}" method="post">

    <!-- Register form fields -->
    {% csrf_token %}
    {% for field in form %}
      {{ field.label_tag | title }}

      <!-- Display field error message -->
      {% for error in field.errors %}
        <div class="error-message"> {{ error }} </div>
      {% endfor %}

      {{ field }}

    {% endfor %}

    <!-- Buttons: confirm registration -->
    <input type="submit" value="Confirm" class="btn" />

  </form>

{% endblock %}